In [1]:
import matplotlib.pyplot as plt
import numpy as np

In [2]:
nums_1d = np.ones((3), dtype = np.int8)
nums_1d

array([1, 1, 1], dtype=int8)

In [3]:
nums_2d = np.ones((3, 4), dtype = np.int8)
nums_2d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [4]:
nums_3d = np.ones((2, 3, 4), dtype = np.int8)
nums_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [5]:
array_nums = np.array([3,4])

In [6]:
array_nums * 2

array([6, 8])

In [7]:
array_nums_more = np.array([10,20])

In [8]:
array_nums * array_nums_more

array([30, 80])

In [9]:
array_nums + array_nums_more

array([13, 24])

In [10]:
array_nums - array_nums_more

array([ -7, -16])

In [11]:
array_nums / array_nums_more

array([0.3, 0.2])

In [12]:
np.ndarray((2,4), np.int8) # garbage data

array([[-102, -103, -103, -103],
       [-103, -103,  -55,   63]], dtype=int8)

In [13]:
from numpy import random
rands = np.random.randn(2,4) * 100 # random

In [14]:
rands.astype('int8')

array([[  81,  103, -123,   51],
       [  47,  123,   93,   -8]], dtype=int8)

In [15]:
#np.save("rands.npy", rands)

In [16]:
for i in rands:
    print(i)

[  81.28666377 -153.35548673 -123.48499138   51.68599016]
[ 47.47586682 123.19871504  93.97401294  -8.61789325]
